### ISSUE TITLE
Attended Events sorted wrongly

### ISSUE THREAD

**Issue by MichaelKohler** [mozilla/community-portal#581] opened 2020-06-15 21:35 UTC
It all seemed to be sorted correctly, until I marked myself attending an event today, which is now shown at the bottom of the list.

![image](https://user-images.githubusercontent.com/330324/84708489-26b71a80-af50-11ea-83ba-4bb87473743d.png)

See also #575

**Comment by Mte90** [comment] 2021-08-02 12:57
duplicate of #575

**Closed by Mte90** 2021-08-02 12:57 UTC
Labels: CU, p2, pr ready
