### ISSUE TITLE
Change copy on the account created

### ISSUE THREAD

**Issue by couci** [mozilla/community-portal#213] opened 2020-01-10 10:49 UTC
Once you create the account you get: "A message here congratulating the user for creating an account and reiterating the benefits of doing so, helping you to connect with other people who like Mozilla. Also an opportunity to encourage the user to put their new account to good use."

I guess we want to change that copy

**Comment by dnaluz** [comment] 2020-01-15 16:49
duplicate of #206

**Closed by dnaluz** 2020-01-15 16:49 UTC
Labels: duplicate

**Comment by dnaluz** [comment] 2020-01-15 18:25
The copy in the figma file needs a response from @LucyeoH.  NOt sure if the copy still applies
