### ISSUE TITLE
Failed update event after second edit the page

### ISSUE THREAD

**Issue by greenbrown** [mozilla/community-portal#670] opened 2020-10-18 06:45 UTC
I've just created an event in the community portal and failed to save the second edit activity of the meeting zoom link.

My event link: [ https://community.mozilla.org/events/hacktoberfest-bersama-komunitas-mozilla-indonesia/]( https://community.mozilla.org/events/hacktoberfest-bersama-komunitas-mozilla-indonesia/)

how to replicate my case:
1. Create new event
2. Edit start time then save change
3. Second edit: I want edit the meeting zoom link
4. failed to update event

**Comment by harshil1712** [comment] 2020-11-08 10:36
I am facing the same issue. I am trying to update the event link, but it fails to do so.

**Comment by couci** [comment] 2021-07-08 14:10
Thanks for reporting, I can also reproduce. I am marking this as p1

**Comment by Mte90** [comment] 2022-03-10 11:15
This bug is happening again?
Can I have a test?

**Comment by couci** [comment] 2022-03-14 16:24
I can't reproduce, I am now able to edit an old event as many times as I want

**Closed** 2022-03-14 17:09 UTC
Labels: bug, p1
