### ISSUE TITLE
People Search With Quotes - Not as I would expect

### ISSUE THREAD

**Issue by emmairwin** [mozilla/community-portal#212] opened 2020-01-09 22:09 UTC
1. I searched randomly for someone with hi in their name.    (enter hi), and a few names turned up where hi was part of their name.
2. I then tried to search for just one of those people using quotes around their name (as per how Google you can make searches more exact.   "Harshil Agrawal"   did not return anyone, and a slash was added to a now empty Search box.

Here is an example using my name
![Mozilla_--_Community_Portal_-_2020-01-09_14 06 29](https://user-images.githubusercontent.com/60618/72108848-4f741d80-32e9-11ea-9204-0b42eef65517.png)

![Mozilla_--_Community_Portal_-_2020-01-09_14 06 43](https://user-images.githubusercontent.com/60618/72108860-58fd8580-32e9-11ea-883f-b0eecbc01d72.png)

I would expect my profile to be returned with this search.

**Comment by davesenior** [comment] 2020-01-10 15:52
Appears to be two issues. One is a search enhancement for quotations. The currently platform that it's built on does not natively support advanced search yet.

The second is special character sanitization is causing a bug and replacing special characters with slashes.

**Comment by Mte90** [comment] 2021-07-29 13:38
It is the WordPress behaviour as it is not so much advanced, basically doesn't support the google dorks.

**Comment by Mte90** [comment] 2021-07-30 09:53
duplicate of https://github.com/mozilla/community-portal/issues/665

**Closed** 2021-07-30 11:46 UTC
Labels: enhancement, p2, to discuss
